M48
; DRILL file {KiCad 9.0.2} date 2025-06-17T12:09:45-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-17T12:09:45-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X176.876Y-55.734
X181.726Y-55.734
T2
X176.576Y-52.704
X182.026Y-52.704
M30
